---
- name: Gather the package facts
  package_facts:
    manager: auto

- name: Download netbird if necessary
  shell: curl -fsSL https://pkgs.netbird.io/install.sh | sh
  when: '''netbird'' not in ansible_facts.packages'

- name: Make sure the latest version of netbird is installed.
  apt:
    update_cache: 'yes'
    name: netbird
    state: latest